---
version: 2.1

jobs:
  build:
    working_directory: ~/hubot-deploy
    docker:
      - image: circleci/node:erbium-buster-browsers-legacy
    steps:
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: yarn install

      - persist_to_workspace:
          root: ~/hubot-deploy
          paths: '*'

  lint:
    working_directory: ~/hubot-deploy
    docker:
      - image: circleci/node:erbium-buster-browsers-legacy
    steps:
      - attach_workspace:
          at: ~/hubot-deploy

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-

      - run:
          name: Install local dependencies
          command: yarn lint

  test:
    working_directory: ~/hubot-deploy
    docker:
      - image: circleci/node:erbium-buster-browsers-legacy
    steps:
      - attach_workspace:
          at: ~/hubot-deploy

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-

      - run:
          name: Install local dependencies
          command: yarn test

workflows:
  version: 2
  ci:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
